package com.demo.entities;// default package
// Generated Jul 13, 2022, 9:23:11 AM by Hibernate Tools 4.3.5.Final

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BookingDetail generated by hbm2java
 */
@Entity
@Table(name = "booking_detail", catalog = "booking")
public class BookingDetail implements java.io.Serializable {

	private Integer id;
	private Booking booking;
	private Room room;
	private Integer quantityAdult;
	private Integer quantityChildren;
	@JsonFormat(pattern = "dd/MM/yyyy",timezone = "Asia/Ho_Chi_Minh")
	private Date checkin;
	@JsonFormat(pattern = "dd/MM/yyyy",timezone = "Asia/Ho_Chi_Minh")
	private Date checkout;
	private boolean status;
	private Set<ServiceDetail> serviceDetails = new HashSet<ServiceDetail>(0);

	public BookingDetail() {
	}

	public BookingDetail(boolean status) {
		this.status = status;
	}

	public BookingDetail(Booking booking, Room room, Integer quantityAdult, Integer quantityChildren, Date checkin,
                         Date checkout, boolean status, Set<ServiceDetail> serviceDetails) {
		this.booking = booking;
		this.room = room;
		this.quantityAdult = quantityAdult;
		this.quantityChildren = quantityChildren;
		this.checkin = checkin;
		this.checkout = checkout;
		this.status = status;
		this.serviceDetails = serviceDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BOOKING_ID")
	public Booking getBooking() {
		return this.booking;
	}

	public void setBooking(Booking booking) {
		this.booking = booking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROOM_ID")
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@Column(name = "QUANTITY_ADULT")
	public Integer getQuantityAdult() {
		return this.quantityAdult;
	}

	public void setQuantityAdult(Integer quantityAdult) {
		this.quantityAdult = quantityAdult;
	}

	@Column(name = "QUANTITY_CHILDREN")
	public Integer getQuantityChildren() {
		return this.quantityChildren;
	}

	public void setQuantityChildren(Integer quantityChildren) {
		this.quantityChildren = quantityChildren;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHECKIN", length = 10)
	public Date getCheckin() {
		return this.checkin;
	}

	public void setCheckin(Date checkin) {
		this.checkin = checkin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHECKOUT", length = 10)
	public Date getCheckout() {
		return this.checkout;
	}

	public void setCheckout(Date checkout) {
		this.checkout = checkout;
	}

	@Column(name = "STATUS", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bookingDetail")
	public Set<ServiceDetail> getServiceDetails() {
		return this.serviceDetails;
	}

	public void setServiceDetails(Set<ServiceDetail> serviceDetails) {
		this.serviceDetails = serviceDetails;
	}

}
