package com.demo.entities;// default package
// Generated Jul 8, 2022, 10:40:31 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "booking")
public class City implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Accomodation> accomodations = new HashSet<Accomodation>(0);

	public City() {
	}

	public City(String name, Set<Accomodation> accomodations) {
		this.name = name;
		this.accomodations = accomodations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<Accomodation> getAccomodations() {
		return this.accomodations;
	}

	public void setAccomodations(Set<Accomodation> accomodations) {
		this.accomodations = accomodations;
	}

}
