package com.demo.entities;// default package
// Generated Jul 8, 2022, 10:40:31 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "booking")
public class Customer implements java.io.Serializable {

	private Integer id;
	private String name;
	private String email;
	private String phone;
	private Date dob;
	private String password;
	private String civilIdentity;
	private Set<Booking> bookings = new HashSet<Booking>(0);
	private Set<Review> reviews = new HashSet<Review>(0);

	public Customer() {
	}

	public Customer(String civilIdentity) {
		this.civilIdentity = civilIdentity;
	}

	public Customer(String name, String email, String phone, Date dob, String password, String civilIdentity,
			Set<Booking> bookings, Set<Review> reviews) {
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.dob = dob;
		this.password = password;
		this.civilIdentity = civilIdentity;
		this.bookings = bookings;
		this.reviews = reviews;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "EMAIL", length = 250)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PHONE", length = 250)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOB", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "PASSWORD", length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "CIVIL_IDENTITY", nullable = false, length = 100)
	public String getCivilIdentity() {
		return this.civilIdentity;
	}

	public void setCivilIdentity(String civilIdentity) {
		this.civilIdentity = civilIdentity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Booking> getBookings() {
		return this.bookings;
	}

	public void setBookings(Set<Booking> bookings) {
		this.bookings = bookings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Review> getReviews() {
		return this.reviews;
	}

	public void setReviews(Set<Review> reviews) {
		this.reviews = reviews;
	}

}
