package com.demo.entities;// default package
// Generated Jul 8, 2022, 10:40:31 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name = "invoice", catalog = "booking")
public class Invoice implements java.io.Serializable {

	private Integer id;
	private Booking booking;
	private Voucher voucher;
	private Double total;
	private Double deposit;
	private Boolean status;
	private Double oweMoney;

	public Invoice() {
	}

	public Invoice(Booking booking, Voucher voucher, Double total, Double deposit, Boolean status, Double oweMoney) {
		this.booking = booking;
		this.voucher = voucher;
		this.total = total;
		this.deposit = deposit;
		this.status = status;
		this.oweMoney = oweMoney;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BOOKING_ID")
	public Booking getBooking() {
		return this.booking;
	}

	public void setBooking(Booking booking) {
		this.booking = booking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VOUCHER_ID")
	public Voucher getVoucher() {
		return this.voucher;
	}

	public void setVoucher(Voucher voucher) {
		this.voucher = voucher;
	}

	@Column(name = "TOTAL", precision = 22, scale = 0)
	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	@Column(name = "DEPOSIT", precision = 22, scale = 0)
	public Double getDeposit() {
		return this.deposit;
	}

	public void setDeposit(Double deposit) {
		this.deposit = deposit;
	}

	@Column(name = "STATUS")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "OWE_MONEY", precision = 22, scale = 0)
	public Double getOweMoney() {
		return this.oweMoney;
	}

	public void setOweMoney(Double oweMoney) {
		this.oweMoney = oweMoney;
	}

}
