package com.demo.entities;// default package
// Generated Jul 8, 2022, 10:40:31 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RoomType generated by hbm2java
 */
@Entity
@Table(name = "room_type", catalog = "booking")
public class RoomType implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer capacity;
	private Integer quantityAdult;
	private Integer quantityChildren;
	private String description;
	private Double price;
	private Set<Room> rooms = new HashSet<Room>(0);

	public RoomType() {
	}

	public RoomType(String name, Integer capacity, Integer quantityAdult, Integer quantityChildren, String description,
			Double price, Set<Room> rooms) {
		this.name = name;
		this.capacity = capacity;
		this.quantityAdult = quantityAdult;
		this.quantityChildren = quantityChildren;
		this.description = description;
		this.price = price;
		this.rooms = rooms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CAPACITY")
	public Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}

	@Column(name = "QUANTITY_ADULT")
	public Integer getQuantityAdult() {
		return this.quantityAdult;
	}

	public void setQuantityAdult(Integer quantityAdult) {
		this.quantityAdult = quantityAdult;
	}

	@Column(name = "QUANTITY_CHILDREN")
	public Integer getQuantityChildren() {
		return this.quantityChildren;
	}

	public void setQuantityChildren(Integer quantityChildren) {
		this.quantityChildren = quantityChildren;
	}

	@Column(name = "DESCRIPTION", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "PRICE", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roomType")
	public Set<Room> getRooms() {
		return this.rooms;
	}

	public void setRooms(Set<Room> rooms) {
		this.rooms = rooms;
	}

}
