package com.demo.entities;// default package
// Generated Jul 13, 2022, 9:23:11 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name = "service", catalog = "booking")
public class Service implements java.io.Serializable {

	private Integer id;
	private Accomodation accomodation;
	private String name;
	private double price;
	private String iconCanvas;
	private boolean status;
	private Set<ServiceDetail> serviceDetails = new HashSet<ServiceDetail>(0);

	public Service() {
	}

	public Service(double price, String iconCanvas, boolean status) {
		this.price = price;
		this.iconCanvas = iconCanvas;
		this.status = status;
	}

	public Service(Accomodation accomodation, String name, double price, String iconCanvas, boolean status,
			Set<ServiceDetail> serviceDetails) {
		this.accomodation = accomodation;
		this.name = name;
		this.price = price;
		this.iconCanvas = iconCanvas;
		this.status = status;
		this.serviceDetails = serviceDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOMODATION_ID")
	public Accomodation getAccomodation() {
		return this.accomodation;
	}

	public void setAccomodation(Accomodation accomodation) {
		this.accomodation = accomodation;
	}

	@Column(name = "NAME", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PRICE", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "ICON_CANVAS", nullable = false, length = 250)
	public String getIconCanvas() {
		return this.iconCanvas;
	}

	public void setIconCanvas(String iconCanvas) {
		this.iconCanvas = iconCanvas;
	}

	@Column(name = "STATUS", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<ServiceDetail> getServiceDetails() {
		return this.serviceDetails;
	}

	public void setServiceDetails(Set<ServiceDetail> serviceDetails) {
		this.serviceDetails = serviceDetails;
	}

}
