package com.demo.entities;// default package
// Generated Jul 8, 2022, 10:40:31 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name = "staff", catalog = "booking")
public class Staff implements java.io.Serializable {

	private int id;
	private Role role;
	private String name;
	private String phone;
	private String email;
	private String civilIdentity;
	private String password;
	private Date dob;
	private String address;
	private Set<Accomodation> accomodations = new HashSet<Accomodation>(0);

	public Staff() {
	}

	public Staff(int id, Role role, String name, String phone, String email, String civilIdentity, String password,
			Date dob, String address) {
		this.id = id;
		this.role = role;
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.civilIdentity = civilIdentity;
		this.password = password;
		this.dob = dob;
		this.address = address;
	}

	public Staff(int id, Role role, String name, String phone, String email, String civilIdentity, String password,
			Date dob, String address, Set<Accomodation> accomodations) {
		this.id = id;
		this.role = role;
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.civilIdentity = civilIdentity;
		this.password = password;
		this.dob = dob;
		this.address = address;
		this.accomodations = accomodations;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLE_ID", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PHONE", nullable = false, length = 100)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "EMAIL", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "CIVIL_IDENTITY", nullable = false, length = 100)
	public String getCivilIdentity() {
		return this.civilIdentity;
	}

	public void setCivilIdentity(String civilIdentity) {
		this.civilIdentity = civilIdentity;
	}

	@Column(name = "PASSWORD", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOB", nullable = false, length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "ADDRESS", nullable = false, length = 250)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<Accomodation> getAccomodations() {
		return this.accomodations;
	}

	public void setAccomodations(Set<Accomodation> accomodations) {
		this.accomodations = accomodations;
	}

}
