package com.demo.entities;// default package
// Generated Jul 8, 2022, 10:40:31 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Voucher generated by hbm2java
 */
@Entity
@Table(name = "voucher", catalog = "booking")
public class Voucher implements java.io.Serializable {

	private Integer id;
	private Accomodation accomodation;
	private Double priceDiscount;
	private Date expDate;
	private Set<Invoice> invoices = new HashSet<Invoice>(0);

	public Voucher() {
	}

	public Voucher(Accomodation accomodation, Double priceDiscount, Date expDate, Set<Invoice> invoices) {
		this.accomodation = accomodation;
		this.priceDiscount = priceDiscount;
		this.expDate = expDate;
		this.invoices = invoices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOMODATION_ID")
	public Accomodation getAccomodation() {
		return this.accomodation;
	}

	public void setAccomodation(Accomodation accomodation) {
		this.accomodation = accomodation;
	}

	@Column(name = "PRICE_DISCOUNT", precision = 22, scale = 0)
	public Double getPriceDiscount() {
		return this.priceDiscount;
	}

	public void setPriceDiscount(Double priceDiscount) {
		this.priceDiscount = priceDiscount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXP_DATE", length = 10)
	public Date getExpDate() {
		return this.expDate;
	}

	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "voucher")
	public Set<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}

}
